name: 'Bikeclub registration field storage'
description: 'Provides storage for registration fields.'
type: 'Content field'
install:
  - link
  - node
  - options
# Contrib  
  - honeypot
  - webform
config:
  strict: false
